### ISSUE TITLE
Tooltips on main address and current network are not working

### ISSUE THREAD

**Issue by nop33** [alephium/desktop-wallet#157] opened 2022-03-15 14:47 UTC
- [x] main address tooltip
- [x] current network tooltip
- [x] overview page address copy to clipboard tooltip
- [x] address detail address copy to clipboard tooltip

https://user-images.githubusercontent.com/1579899/158403936-a6ba5b9a-32e2-4e91-af6b-f48c61419bca.mp4

**Comment by lf94** [comment] 2022-03-16 14:58
* [ ] QR Code tooltip not working

**Comment by lf94** [comment] 2022-03-16 15:14
o7, I made a bad assumption - I saw QR Code used the Tooltip component and just assumed it should say "QR Code" :laughing: .  I won't do it just so the issue remains focused.

**Comment by nop33** [comment] 2022-03-16 15:24
It's a very logical assumption, I also felt for it

**Comment by mvaivre** [comment] 2022-03-16 16:02
https://user-images.githubusercontent.com/6715943/158633698-5087dbf3-5d83-425c-b189-84d3ed3f4a00.mov

I can't reproduce it :/

**Comment by lf94** [comment] 2022-03-16 16:04
Was able to reproduce here :rocket: 

Resolved by https://github.com/alephium/alephium-wallet/pull/163

**Closed as completed** 2022-03-16 18:08 UTC
Labels: bug
