### ISSUE TITLE
Send modal: adding then removing assets provokes an error

### ISSUE THREAD

**Issue by mvaivre** [alephium/desktop-wallet#666] opened 2023-04-29 12:58 UTC
To reproduce : 
- Add multiple assets
- Select one with i > 0 to set amount.
- Delete assets.

**Comment by nop33** [comment] 2023-05-01 10:03
I cannot reproduce this... 

https://user-images.githubusercontent.com/1579899/235438357-3ca46f27-f1f2-4064-abf6-5e8e1f1eb5cd.mp4

**Comment by nop33** [comment] 2023-05-01 10:03
Ah, just noticed that you probably fixed this here: https://github.com/alephium/desktop-wallet/commit/03f5f0965dd6243e6944633115ca5b7eafa426c9

**Comment by mvaivre** [comment] 2023-05-02 03:21
Yes I referenced it in said commit to make sure it doesn't go unnoticed 😆 

<img width="555" alt="image" src="https://user-images.githubusercontent.com/6715943/235572798-97daea7f-b8dd-41e9-a8c8-a9a745c894bd.png">

**Comment by nop33** [comment] 2023-05-02 08:47
I saw the issue as unassigned and not in progress and didn't notice the reference! Will pay more attention next time ;)

**Comment by mvaivre** [comment] 2023-05-02 08:59
And I'll update the issue status / assignee 👌

**Comment by nop33** [comment] 2023-05-03 20:03
merged in v2.0. Closing.

**Closed by nop33** 2023-05-03 20:03 UTC
Labels: bug
