### ISSUE TITLE
Fix table alignement issues

### ISSUE THREAD

**Issue by mvaivre** [alephium/desktop-wallet#347] opened 2022-09-05 07:48 UTC
<img width="959" alt="image" src="https://user-images.githubusercontent.com/6715943/188396318-1cf0b916-ff07-4e6a-9472-8345983e2e03.png">

In the tables, columns should be of fixed length (data should be aligned), and the received / send icon should be aligned vertically.

**Comment by LeeAlephium** [comment] 2022-09-05 22:55
Hm, wonder if this was caused by rebase. I spent specific time on being sure alignment was perfect! :scream_cat:

**Comment by LeeAlephium** [comment] 2022-09-06 12:38
@mvaivre I think I had already fixed this in https://github.com/alephium/desktop-wallet/pull/344 - I'm not seeing any alignment issues

**Comment by LeeAlephium** [comment] 2022-09-06 12:56
@mvaivre rebase done

**Comment by mvaivre** [comment] 2022-09-06 16:35
I haven't tested it yet, but based on your screenshot I see two things:

The "received" arrow is still not centered
<img width="49" alt="image" src="https://user-images.githubusercontent.com/6715943/188688937-ca6d3525-ac3e-4145-aef7-fb5e9d3ca652.png">

The "from" and "to" badges don't have the same color.

**Comment by LeeAlephium** [comment] 2022-09-06 16:37
Mmm, I'll have to manually adjust the vertical centering then as I did horizontal...

> The "from" and "to" badges don't have the same color.

This is because they use different theme colors like in the mock ups, it's just way more noticeable in light mode - did we just want to make them the same overall then?

**Comment by mvaivre** [comment] 2022-09-06 16:41
Just tested, the down arrow looks better now... that's weird. The alignement issue still remains though, when amounts are large:

<img width="983" alt="image" src="https://user-images.githubusercontent.com/6715943/188690201-7b6d4e3d-45d2-42a2-9cb3-4b1863c8c5dc.png">

And yes, the "from" and "to" label should have the same color. Let's choose the darker one for the light theme.

**Comment by LeeAlephium** [comment] 2022-09-06 17:36
The arrow itself is funky it looks like... In any case, I've done some further micro-adjustments to hopefully make them centered enough. I think arrow is not symmetrical, but slightly off on one side...

**Comment by nop33** [comment] 2022-09-26 14:44
I think this issue is not relevant anymore, is it?

**Comment by LeeAlephium** [comment] 2022-09-26 14:58
For some reason GitHub has stopped auto-closing issues (maybe we reconfigured the repo to act this way) - yeah, anything you see that needs closing because it was merged please close it :pray:

**Closed by LeeAlephium** 2022-09-26 14:58 UTC
Labels: improvement

**Comment by LeeAlephium** [comment] 2022-09-26 15:27
Ah, that sucks :) Oh well, no problem doing it manually anyway.
