### ISSUE TITLE
Fetch pending transactions

### ISSUE THREAD

**Issue by mvaivre** [alephium/desktop-wallet#323] opened 2022-08-09 15:03 UTC
Placeholder. Depends on https://github.com/alephium/explorer-backend/issues/95

**Comment by LeeAlephium** [comment] 2022-09-26 20:15
Brief on what needs to be done:

1. After unlock, fetch pending (create PendingTxs in AddressContext)
2. Perpetually fetch pending addresses every (n + b) seconds (give time for the Tx to propagate to nodes but not yet be confirmed) - n is time to propagate, b is a fraction of avg. block time (we'll go with half since the chances of it being confirmed then is rare) - create an interval timer in AddressContext

Sending a Tx this won't matter, since we immediately add this as a PendingTx already.

I think that's about all, the API itself is quite simple, since `addresses/<address>/unconfirmed-transactions` can be called on all the addresses in AddressContext

**Comment by LeeAlephium** [comment] 2022-09-26 20:16
I'm going to go ahead and do it, I think it'll take half a day at most :leg:

**Comment by LeeAlephium** [comment] 2022-09-26 21:35
Taken about 1 hour and nearly done :sparkles:

**Comment by nop33** [comment] 2022-10-03 13:05
Closed via #374

**Closed by nop33** 2022-10-03 13:05 UTC
Labels: improvement
