### ISSUE TITLE
Contact list

### ISSUE THREAD

**Issue by mvaivre** [alephium/desktop-wallet#355] opened 2022-09-09 07:56 UTC
TBD more precisely.

Draft:

We want to let our users select a recipient with confidence. One could send a TX to themselves or to an external address.
- To themselves : the user should be able to select the receiving address by selecting its label.
- To an external recipient : a contact list should be available, avoiding copy pasting mistakes.

TODO:

- [ ] Design

**Comment by nop33** [comment] 2022-09-21 09:40
Possible duplicate of https://github.com/alephium/desktop-wallet/issues/182? 😄

**Comment by mvaivre** [comment] 2022-09-21 11:47
Yes! I knew there was one task already!

**Comment by nop33** [comment] 2023-02-27 15:03
@mvaivre shall we close this issue? I think we got everything we need merged in 2.0 already!

**Comment by nop33** [comment] 2023-03-08 12:56
I'll close this as it's merged in V2.0

**Closed by nop33** 2023-03-08 12:56 UTC
Labels: feature, investigation
