### ISSUE TITLE
Improve error handling when not enough ALPH is available to cover transaction fees

### ISSUE THREAD

**Issue by mvaivre** [alephium/desktop-wallet#734] opened 2023-06-21 08:28 UTC
Monitor error handling progress on the node. If needed, patch this on the client side by specifying which asset amount isn't enough and properly format amounts for display.

![image](https://github.com/alephium/desktop-wallet/assets/6715943/643ed3c4-d30d-4fd5-a700-7ea2f0b6998f)

**Comment by nop33** [comment] 2023-11-16 08:56
Duplicate of https://github.com/alephium/desktop-wallet/issues/734

Closing.

**Closed by nop33** 2023-11-16 08:56 UTC
