### ISSUE TITLE
Allow tweaking settings when the app can't connect to a network

### ISSUE THREAD

**Issue by mvaivre** [alephium/desktop-wallet#422] opened 2022-11-02 14:06 UTC
As of today, a loading screen is spinning forever if the wallet can't reach the network on startup. The user can't interact with the app. We should allow users to tweak the network settings when this happens.

**Comment by nop33** [comment] 2022-11-15 13:43
Are you sure this is the case? I don't have that spinning when in offline mode...

**Comment by nop33** [comment] 2022-11-15 13:45
https://user-images.githubusercontent.com/1579899/201934946-a9c8c2d7-0d7d-4a42-b455-495c0de92ad7.mp4

**Comment by nop33** [comment] 2022-11-24 13:01
I am closing this issue since it's not reproducable. @mvaivre feel free to open it again if I am wrong.

**Closed by nop33** 2022-11-24 13:01 UTC
